apiVersion: v1
kind: Service
spec:
  selector:
    app: kafka-neo4j-connector
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
metadata:
  name: kafka-neo4j-connector-ser
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
        - name: kafka-neo4j-connector
          image: veedata/kafka-neo4j-connect
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8083
metadata:
  name: kafka-neo4j-connector-dep
  labels:
    app: kafka-neo4j-connector

